"""create users, refresh tokens and investor profiles

Revision ID: 423f148f12a1
Revises: 
Create Date: 2026-10-06 04:59:54.195064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '423f148f12a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('investor', 'architect', 'admin', name='user_role', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('onboarding', 'pending_review', 'active', 'suspended', name='user_status', native_enum=False, length=20), server_default='onboarding', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('investor', 'architect', 'admin')", name=op.f('ck_users_role_valid')),
    sa.CheckConstraint("status IN ('onboarding', 'pending_review', 'active', 'suspended')", name=op.f('ck_users_status_valid')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_users_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('google_sub', name=op.f('uq_users_google_sub'))
    )
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('investor_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('focus', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('sectors', postgresql.ARRAY(sa.String(length=40)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('looking_for', sa.Text(), nullable=False),
    sa.Column('capital_range', sa.Enum('under_10k', '10k_50k', '50k_250k', '250k_1m', 'over_1m', 'exploring', name='investor_capital_range', native_enum=False, length=20), nullable=False),
    sa.Column('deployment_timeline', sa.Enum('now', 'within_3_months', 'within_12_months', 'exploring', name='investor_deployment_timeline', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("capital_range IN ('under_10k', '10k_50k', '50k_250k', '250k_1m', 'over_1m', 'exploring')", name=op.f('ck_investor_profiles_capital_range_valid')),
    sa.CheckConstraint("deployment_timeline IN ('now', 'within_3_months', 'within_12_months', 'exploring')", name=op.f('ck_investor_profiles_deployment_timeline_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_investor_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_investor_profiles'))
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('remember_me', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('investor_profiles')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
